name: clang-format

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@v0.13
      with:
        source: 'include'
        extensions: 'hpp,cpp'
        clangFormatVersion: 13
        style: llvm
